name: Build and Deploy Jekyll Site

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: false

      - name: Clean previous builds
        run: |
          rm -rf _site .sass-cache .jekyll-cache .jekyll-metadata
          rm -f Gemfile.lock

      - name: Configure Bundler
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle config set --local deployment false

      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --baseurl "/eneplus" --trace
        env:
          JEKYLL_ENV: production

      - name: Verify build
        run: |
          if [ ! -d "_site" ] || [ -z "$(ls -A _site)" ]; then
            echo "Error: _site directory is empty or missing"
            exit 1
          fi
          echo "Build verification successful"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
